import React, { FC, ReactNode } from 'react';
import type { Metadata, Viewport } from 'next';

// CSS
import '@/styles/globals.css';

// Fonts
import { primaryFont, secondaryFont } from '@/public/fonts/fonts';

// Layout
import Layout from '@/components/Layout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  themeColor: '#1F2937',
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={`${primaryFont.variable} ${secondaryFont.variable}`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
};

export default RootLayout;
